# Generated by Django 5.2.12 on 2026-03-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('on_progress', 'On Progress'), ('rejected', 'Rejected'), ('completed', 'Completed')], max_length=20)),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('on_progress', 'On Progress'), ('rejected', 'Rejected'), ('completed', 'Completed')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('maintenance', 'Maintenance'), ('cleaning', 'Cleaning'), ('security', 'Security'), ('supplies', 'Office Supplies'), ('vehicle', 'Vehicle'), ('facility', 'Facility'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('on_progress', 'On Progress'), ('rejected', 'Rejected'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Request',
                'verbose_name_plural': 'Service Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
