# Generated by Django 5.2.12 on 2026-03-10 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0003_alter_servicerequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['created_at'], 'verbose_name': 'Service Request', 'verbose_name_plural': 'Service Requests'},
        ),
    ]
