# Generated by Django 5.2.12 on 2026-03-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('ga', 'General Affair')], db_index=True, default='employee', max_length=20),
        ),
    ]
