# Generated by Django 5.2.12 on 2026-03-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('ga', 'General Affair'), ('karyawan', 'Karyawan')], db_index=True, default='karyawan', max_length=20),
        ),
    ]
